# Site
repository: martin-morek/resume
favicon: img/favicon.ico

# Personal info
name: Martin Morek
title: Software Developer
email: martin.morek@gmail.com

# Social links
twitter_username: morek_martin
github_username:  martin-morek
linkedin_username: martinmorek

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: img/martin-morek.jpg
about_content: |
  I am a reliable and skilled software developer with more than five years of professional programming experience,
  last three years primarily focusing on Scala language. I love functional programming and I’m always eager to learn new skills.
  I have worked in different companies from small start-up to huge corporation which helped me to gain lot of experience
  as well as different points of view on software development. I’m freelancer because I consider it to be the best work-life
  balance solution for me. I get to do what I love and get paid for it, and at the same time I have a freedom to work
  on my own self-development.


  <mark>Scala</mark> <mark>Java</mark> <mark>SQL</mark> <mark>Functional programming</mark> <mark>Play framework</mark> <mark>Spring boot</mark> <mark>Akka</mark> <mark>Event sourcing</mark>

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
    Alongside my interests in programming and software engineering some of my other interests and hobbies are:
      - swimming
      - traveling
      - cooking
      - books
      - movies

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
