# Site
repository: martin-morek/resume
favicon: img/favicon.ico

# Personal info
name: Martin Morek
title: Software Developer
email: martin.morek@gmail.com

# Social links
twitter_username: morek_martin
github_username:  martin-morek
linkedin_username: martinmorek

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: img/picture.jpg
about_content: |
  I'm a programming geek with enthusiasm about everything related to technology, from IoT gadgets to software development. I love learning a new things and trying them in a practice.

  <mark>Scala</mark> <mark>Java</mark> <mark>SQL</mark> <mark>Ruby</mark> <mark>JavaScript</mark> <mark>Play framework</mark> <mark>Spring boot</mark> <mark>Akka</mark> <mark>Event sourcing</mark>

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
    Alongside my interests in programming and software engineering some of my other interests and hobbies are:
      - traveling
      - cooking
      - books
      - movies

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
